export const HABIT_LIBRARY = [
  // ── VITALITY ──────────────────────────────────────────────────
  {
    id: "vit_1",
    name: "Morning hydration",
    stat: "vitality",
    tier: 1,
    keystone: false,
    xpReward: 10,
    daysToAutomate: { min: 4, median: 14, max: 21 },
    why: "Fastest-forming habit. Body is dehydrated after sleep. Even mild dehydration impairs attention and memory.",
    cue: "Glass of water on your nightstand",
    routine: "Drink full glass before touching your phone",
    reward: "Immediate alertness + first win of the day",
    starter: "One glass, any time before breakfast",
    unlock: "Water + electrolytes + no phone until finished",
    unlocksAt: 14,
  },
  {
    id: "vit_2",
    name: "Daily movement",
    stat: "vitality",
    tier: 2,
    keystone: true,
    xpReward: 30,
    daysToAutomate: { min: 30, median: 66, max: 100 },
    why: "Single most impactful keystone habit. Triggers better eating, sleep, mood, focus as side effects. Increases BDNF — the protein your brain uses to build connections.",
    cue: "Shoes by the bed the night before",
    routine: "20–30 min walk, run, or any movement",
    reward: "Endorphin release + XP + identity shift",
    starter: "5-min walk outside, no excuses",
    unlock: "30-min jog or gym session 3×/week",
    unlocksAt: 21,
  },
  {
    id: "vit_3",
    name: "Consistent sleep schedule",
    stat: "vitality",
    tier: 2,
    keystone: true,
    xpReward: 25,
    daysToAutomate: { min: 14, median: 30, max: 66 },
    why: "Sleep deprivation reduces working memory by 40%. Consistent sleep/wake time — even on weekends — is the #1 cognitive performance intervention.",
    cue: "Set both a SLEEP alarm and a wake alarm",
    routine: "Same bedtime ±30 min every day including weekends",
    reward: "Clear head by morning 3, energy compounds weekly",
    starter: "Set a sleep alarm tonight — just the alarm",
    unlock: "No screens 30 min before bed + sleep alarm",
    unlocksAt: 14,
  },
  {
    id: "vit_4",
    name: "No screens before bed",
    stat: "vitality",
    tier: 2,
    keystone: false,
    xpReward: 15,
    daysToAutomate: { min: 30, median: 45, max: 66 },
    why: "Blue light suppresses melatonin by up to 3 hours. Screens keep the brain in reactive mode, preventing the cognitive wind-down needed for deep sleep.",
    cue: "Set a 'last screen' alarm 30 min before bed",
    routine: "Book, journaling, or light stretching instead",
    reward: "Fall asleep faster, better dream recall",
    starter: "Phone in another room 10 min before sleep",
    unlock: "Full 30-min screen-free wind-down ritual",
    unlocksAt: 30,
  },

  // ── FOCUS ─────────────────────────────────────────────────────
  {
    id: "foc_1",
    name: "No phone first 30 min",
    stat: "focus",
    tier: 2,
    keystone: true,
    xpReward: 20,
    daysToAutomate: { min: 21, median: 45, max: 66 },
    why: "Phone-checking first thing primes the brain for reactive, distracted mode all day. Morning hours are peak cognitive energy — protect them.",
    cue: "Phone stays face-down until first habit is complete",
    routine: "30 min phone-free after waking",
    reward: "Notice how differently you feel by 9am",
    starter: "No phone until after breakfast",
    unlock: "60-min phone-free morning + DND mode",
    unlocksAt: 21,
  },
  {
    id: "foc_2",
    name: "Daily breathing / mindfulness",
    stat: "focus",
    tier: 2,
    keystone: false,
    xpReward: 20,
    daysToAutomate: { min: 30, median: 56, max: 66 },
    why: "5–10 min daily mindfulness strengthens the prefrontal cortex and reduces amygdala reactivity. Structural changes take 8 weeks but subjective focus improves in week 1.",
    cue: "Right after waking, before anything else",
    routine: "5 min box breathing or silent sitting",
    reward: "Calm, clear baseline for the entire day",
    starter: "1 min deep breathing after waking",
    unlock: "10 min Wim Hof breathing or guided meditation",
    unlocksAt: 21,
  },
  {
    id: "foc_3",
    name: "Pomodoro focus block",
    stat: "focus",
    tier: 2,
    keystone: false,
    xpReward: 20,
    daysToAutomate: { min: 21, median: 45, max: 66 },
    why: "Brief breaks significantly improve attention and prevent mental fatigue. 25-min focused blocks with 5-min breaks match natural attention cycles.",
    cue: "Open your #1 task, set timer, close all other tabs",
    routine: "25 min pure focus, zero notifications",
    reward: "Progress feeling + earned rest",
    starter: "One 25-min block per day, any task",
    unlock: "3–4 blocks with scheduled breaks, no phone",
    unlocksAt: 14,
  },

  // ── WILL ──────────────────────────────────────────────────────
  {
    id: "wil_1",
    name: "Make your bed",
    stat: "will",
    tier: 1,
    keystone: true,
    xpReward: 10,
    daysToAutomate: { min: 7, median: 14, max: 21 },
    why: "The easiest keystone habit. Small wins in one area strengthen discipline everywhere else. The real reward is the identity shift: 'I am someone who does what they say they'll do.'",
    cue: "Feet hit the floor in the morning",
    routine: "Make bed before leaving the bedroom",
    reward: "Visual order + first win of the day + momentum",
    starter: "Just the top blanket, takes 30 seconds",
    unlock: "Full bed + tidy nightstand + room scan",
    unlocksAt: 14,
  },
  {
    id: "wil_2",
    name: "Cold shower",
    stat: "will",
    tier: 2,
    keystone: true,
    xpReward: 25,
    daysToAutomate: { min: 30, median: 45, max: 66 },
    why: "Dopamine +250%, norepinephrine +530% for hours after. Doing something your body resists every morning is the #1 willpower training exercise.",
    cue: "End of your regular warm shower",
    routine: "Turn to cold, breathe through it for 30 seconds",
    reward: "Dopamine surge + proof you can do hard things",
    starter: "10 seconds cold at the very end",
    unlock: "Full 60–90 sec cold shower, morning only",
    unlocksAt: 14,
  },
  {
    id: "wil_3",
    name: "One hard thing first",
    stat: "will",
    tier: 3,
    keystone: false,
    xpReward: 30,
    daysToAutomate: { min: 45, median: 90, max: 120 },
    why: "The prefrontal cortex — willpower center — grows physically when you push through resistance. Identity-based framing: 'I am someone who does hard things' increases adherence by 32%.",
    cue: "Written the night before — specific, not vague",
    routine: "Do it before easier tasks, no warm-up procrastination",
    reward: "Relief + pride + compounding confidence",
    starter: "One scary email or task done before noon",
    unlock: "Hard thing + no shortcuts all day",
    unlocksAt: 30,
  },
  {
    id: "wil_4",
    name: "One-domain discipline rule",
    stat: "will",
    tier: 2,
    keystone: true,
    xpReward: 20,
    daysToAutomate: { min: 30, median: 60, max: 90 },
    why: "People who increased willpower in ONE area became more disciplined everywhere — less junk food, alcohol, TV, depression. The daily repetition is what matters.",
    cue: "Pick one rule. Write it. Post it somewhere visible.",
    routine: "Follow the rule with zero exceptions today",
    reward: "Spillover discipline across your entire life",
    starter: "No snacking after 9pm — just that one rule",
    unlock: "Strict dietary or spending rule, logged daily",
    unlocksAt: 21,
  },

  // ── OUTPUT ────────────────────────────────────────────────────
  {
    id: "out_1",
    name: "Top 3 tasks (night before)",
    stat: "output",
    tier: 1,
    keystone: true,
    xpReward: 15,
    daysToAutomate: { min: 14, median: 21, max: 45 },
    why: "Eliminates morning decision fatigue. Writing them the night before offloads open loops from working memory, improving sleep. Specific goals create a dopamine-driven feedback loop.",
    cue: "Last thing before sleep, same notebook or app",
    routine: "Write 3 specific tasks for tomorrow — nothing vague",
    reward: "Better sleep + instant clarity on waking",
    starter: "One task written on paper tonight",
    unlock: "3 tasks + time blocks + estimated durations",
    unlocksAt: 14,
  },
  {
    id: "out_2",
    name: "Morning deep work block",
    stat: "output",
    tier: 3,
    keystone: false,
    xpReward: 35,
    daysToAutomate: { min: 45, median: 90, max: 120 },
    why: "Cognitive energy is highest in the morning. Deep work in the first 90 min — before email, meetings, messages — compounds dramatically over time.",
    cue: "Phone in drawer, coffee ready, task already written",
    routine: "90 min no-interruption work on #1 priority",
    reward: "Day's most important work done by 10am",
    starter: "30-min focused block before checking anything",
    unlock: "90-min protected morning block, every day",
    unlocksAt: 45,
  },
  {
    id: "out_3",
    name: "Weekly review",
    stat: "output",
    tier: 3,
    keystone: false,
    xpReward: 25,
    daysToAutomate: { min: 45, median: 90, max: 120 },
    why: "The meta-habit. Participants who kept daily logs lost twice as much weight because they could see patterns previously invisible. The weekly review closes open loops, surfaces what's working.",
    cue: "Every Sunday, same time, same chair",
    routine: "30 min: what worked, what didn't, plan next week",
    reward: "Clarity + control + compounding results",
    starter: "5-min Sunday brain dump, no structure needed",
    unlock: "Full GTD-style weekly review with habit audit",
    unlocksAt: 30,
  },

  // ── PRESENCE ──────────────────────────────────────────────────
  {
    id: "pre_1",
    name: "Gratitude journaling",
    stat: "presence",
    tier: 1,
    keystone: true,
    xpReward: 15,
    daysToAutomate: { min: 14, median: 21, max: 30 },
    why: "3 specific things daily shifts the brain's default from threat-scanning to opportunity-spotting. Linked to reduced anxiety, better sleep, improved relationships.",
    cue: "With morning coffee OR last thing before bed",
    routine: "Write 3 specific things — not generic, not repeated",
    reward: "Mood lift within 2 weeks. Compounding over time.",
    starter: "One thing, no journal needed, just say it aloud",
    unlock: "3 specific things + one sentence on why each matters",
    unlocksAt: 14,
  },
  {
    id: "pre_2",
    name: "Reach out to one person",
    stat: "presence",
    tier: 1,
    keystone: false,
    xpReward: 10,
    daysToAutomate: { min: 21, median: 30, max: 45 },
    why: "Social connection is among the strongest long-term health predictors. 1 message per day builds relationships that compound over years.",
    cue: "Morning coffee or lunch break",
    routine: "Text or message someone — initiate, don't just respond",
    reward: "Warmth, replies, strengthened bond",
    starter: "One text to anyone, any reason",
    unlock: "Meaningful check-in or set a real call",
    unlocksAt: 21,
  },
  {
    id: "pre_3",
    name: "Say no to one thing",
    stat: "presence",
    tier: 2,
    keystone: false,
    xpReward: 20,
    daysToAutomate: { min: 30, median: 60, max: 90 },
    why: "Boundaries are a form of self-respect that signals to the brain: 'my time has value.' Every unnecessary yes drains cognitive and emotional resources.",
    cue: "Any request that creates a 'ugh' feeling",
    routine: "Decline politely and without guilt",
    reward: "Protected time + self-respect + energy saved",
    starter: "Decline one low-value commitment this week",
    unlock: "Audit all recurring commitments, cut one",
    unlocksAt: 30,
  },

  // ── WISDOM ────────────────────────────────────────────────────
  {
    id: "wis_1",
    name: "Read 10 pages daily",
    stat: "wisdom",
    tier: 1,
    keystone: true,
    xpReward: 15,
    daysToAutomate: { min: 21, median: 45, max: 66 },
    why: "10 pages = ~15 min = 12+ books per year. Knowledge compounds. Morning formation beats evening. Pair with existing habit via habit stacking.",
    cue: "Same time, same place daily — pair with coffee",
    routine: "10 pages minimum — physical book over phone",
    reward: "Story immersion + XP + knowledge compound",
    starter: "5 pages of any book you actually want to read",
    unlock: "10 pages + 1-sentence reflection note after",
    unlocksAt: 21,
  },
  {
    id: "wis_2",
    name: "Learn one new thing",
    stat: "wisdom",
    tier: 1,
    keystone: false,
    xpReward: 10,
    daysToAutomate: { min: 14, median: 30, max: 45 },
    why: "Curiosity-driven learning releases dopamine at the cue stage — anticipation of interesting content. This makes it self-reinforcing faster than duty-based habits.",
    cue: "Lunch break or commute",
    routine: "One video, article, or podcast — curiosity-driven",
    reward: "Dopamine from discovery",
    starter: "One YouTube video on anything you're curious about",
    unlock: "Take notes + apply or share one idea",
    unlocksAt: 14,
  },
  {
    id: "wis_3",
    name: "Apply and teach back",
    stat: "wisdom",
    tier: 3,
    keystone: false,
    xpReward: 25,
    daysToAutomate: { min: 45, median: 90, max: 120 },
    why: "The Feynman Technique: explaining what you learned reveals gaps in understanding and cements retention. Learning to apply + explain is the gap between consuming information and actually gaining wisdom.",
    cue: "After reading or learning something",
    routine: "Write 3 sentences: what it was, why it matters, how you'll use it",
    reward: "Real comprehension + shareable insight",
    starter: "One-sentence lesson from today's reading",
    unlock: "Write a short post, note, or explain it to someone",
    unlocksAt: 30,
  },
];

export const STARTER_HABIT_IDS = ["vit_3", "foc_1", "wil_1", "out_1", "pre_1", "wis_2"];

export const STAT_META = {
  vitality: { label: "VITALITY",  icon: "💪", color: "#ef4444", description: "Physical health" },
  focus:    { label: "FOCUS",     icon: "🧠", color: "#3b82f6", description: "Mental clarity & attention" },
  will:     { label: "WILL",      icon: "⚔️",  color: "#f59e0b", description: "Discipline & self-control" },
  output:   { label: "OUTPUT",    icon: "⚡", color: "#8b5cf6", description: "Productivity & deep work" },
  presence: { label: "PRESENCE",  icon: "🤝", color: "#ec4899", description: "Social & emotional health" },
  wisdom:   { label: "WISDOM",    icon: "📚", color: "#10b981", description: "Learning & growth" },
};

export const TITLES = [
  // Foundation
  { id: "t_beginning",    label: "The Beginning",       category: "foundation", condition: d => d.dayCount >= 1 },
  { id: "t_first_blood",  label: "First Blood",         category: "foundation", condition: d => d.globalStreak >= 7 },
  { id: "t_consistent",   label: "The Consistent One",  category: "foundation", condition: d => d.globalStreak >= 14 },
  { id: "t_comeback",     label: "Comeback Kid",        category: "foundation", condition: d => d.hadComeback === true },
  // Stat level 2
  { id: "t_the_living",   label: "The Living",          category: "vitality",   condition: d => (d.stats?.vitality?.level ?? 1) >= 2 },
  { id: "t_clear_mind",   label: "Clear Mind",          category: "focus",      condition: d => (d.stats?.focus?.level ?? 1) >= 2 },
  { id: "t_disciplined",  label: "The Disciplined",     category: "will",       condition: d => (d.stats?.will?.level ?? 1) >= 2 },
  { id: "t_the_builder",  label: "The Builder",         category: "output",     condition: d => (d.stats?.output?.level ?? 1) >= 2 },
  { id: "t_connected",    label: "Connected",           category: "presence",   condition: d => (d.stats?.presence?.level ?? 1) >= 2 },
  { id: "t_student",      label: "The Student",         category: "wisdom",     condition: d => (d.stats?.wisdom?.level ?? 1) >= 2 },
  // Stat level 5
  { id: "t_unbreakable",  label: "Unbreakable",         category: "vitality",   condition: d => (d.stats?.vitality?.level ?? 1) >= 5 },
  { id: "t_iron_focus",   label: "Iron Focus",          category: "focus",      condition: d => (d.stats?.focus?.level ?? 1) >= 5 },
  { id: "t_unshakeable",  label: "Unshakeable",         category: "will",       condition: d => (d.stats?.will?.level ?? 1) >= 5 },
  { id: "t_deep_worker",  label: "Deep Worker",         category: "output",     condition: d => (d.stats?.output?.level ?? 1) >= 5 },
  { id: "t_present",      label: "Fully Present",       category: "presence",   condition: d => (d.stats?.presence?.level ?? 1) >= 5 },
  { id: "t_scholar",      label: "The Scholar",         category: "wisdom",     condition: d => (d.stats?.wisdom?.level ?? 1) >= 5 },
  // Automation
  { id: "t_cold_blooded",   label: "Cold Blooded",       category: "automation", automationHabit: "wil_2" },
  { id: "t_early_riser",    label: "The Early Riser",    category: "automation", automationHabit: "foc_1" },
  { id: "t_iron_bed",       label: "Iron Bed",           category: "automation", automationHabit: "wil_1" },
  { id: "t_the_scribe",     label: "The Scribe",         category: "automation", automationHabit: "pre_1" },
  { id: "t_deep_reader",    label: "Deep Reader",        category: "automation", automationHabit: "wis_1" },
  { id: "t_nightly_plan",   label: "Nightly Planner",    category: "automation", automationHabit: "out_1" },
  // Phase
  { id: "t_foundations",    label: "Foundations Laid",   category: "phase",      condition: d => d.currentPhase >= 2 },
  { id: "t_stacking",       label: "Stacking Up",        category: "phase",      condition: d => d.currentPhase >= 3 },
  { id: "t_automated_human",label: "Automated Human",    category: "phase",      condition: d => d.playerHabits?.some(h => h.status === "automated") },
];

export const STREAK_MILESTONES = [3, 7, 14, 21, 30, 66];

export const STREAK_MESSAGES = {
  3:  "3-DAY STREAK 🔥 The habit loop is forming.",
  7:  "ONE WEEK 🔥🔥 Your brain is rewiring. Real.",
  14: "14 DAYS. Upgrade available. Check your habits.",
  21: "21 DAYS 🔥🔥🔥 You're past the hardest part.",
  30: "30 DAYS. New habit slot unlocked. You've earned it.",
  66: "66 DAYS ✓ AUTOMATED. This is who you are now.",
};

export const COACH_MESSAGES = {
  perfect: [
    "LEGENDARY. Every single enemy defeated.\nThe version of you from last month is shaking.",
    "Full clear. You don't need motivation.\nYou have systems now.",
    "Every day you do this, the old you gets weaker.\nDon't stop.",
  ],
  good: [
    "Solid run. The ones you missed? Tomorrow.\nYour streak is still alive.",
    "Progress is progress. The science says 66 days.\nYou're still in the fight.",
    "Good. Not legendary. You know what to do tomorrow.",
  ],
  rough: [
    "We take the loss. We don't stay down.\nOne bad day doesn't erase your streak.",
    "The comeback is part of the story.\nSee you tomorrow.",
    "The game isn't over. It never is.\nGet back up.",
  ],
  zero: [
    "You didn't show up today.\nThat's data, not a verdict.\nThe frozen streak is waiting. Don't lose it.",
  ],
};
